### ISSUE TITLE
`routef` shadows another `routef`

### ISSUE THREAD

**Issue by vasily-kirichenko** [giraffe-fsharp/Giraffe#176]
I have the following routes:

```fsharp
subRoute "/api"
    (choose [
        subRoute "/hosts"
            (choose [
                route "" >=>  text "a"
                routef "/%s" (fun host -> text "c")
                routef "/%s/%s/%i/log" (fun (host, app, pid) -> text "foo")
            ])
     ])
```
`/api` works
`/api/hosts` works
`/api/hosts/foo` works
but 
`/api/hosts/a/b/33/log` - does not.

If I remove `routef "/%s"`, then `routef "/%s/%s/%i/log"` starts working. It seems the first one is too "greedy" and "shadows" the last one?

**Comment by vasily-kirichenko** [comment]
```
dotnet\dotnet.exe" ...Server.dll
Hosting environment: Production
Content root path: ...
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at KlSrl.Insight.Server.Utils.makeGetRequest@46-3.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Utils.fs:line 46
   at Giraffe.TaskBuilder.tryFinally[a](FSharpFunc`2 step, FSharpFunc`2 fin)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Server.App.webApp@61-16.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Program.fs:line 61
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.handlerWithRootedPath@62-2.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.handlerWithRootedPath@62-2.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@39-5.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Server.App.Invoke@133-2.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Program.fs:line 133
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@64-8.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at KlSrl.Insight.Server.Utils.makeGetRequest@46-3.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Utils.fs:line 46
   at Giraffe.TaskBuilder.tryFinally[a](FSharpFunc`2 step, FSharpFunc`2 fin)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Server.App.webApp@61-16.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Program.fs:line 61
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.handlerWithRootedPath@62-2.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.handlerWithRootedPath@62-2.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.HttpHandlers.chooseHttpFunc@97-1.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@39-5.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Server.App.Invoke@133-2.Invoke(Unit unitVar0) in D:\WLCR\stash\KlSrl.Insight\src\Server\Program.fs:line 133
   at Giraffe.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@64-8.Invoke(Unit unitVar0)
   at Giraffe.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
```

**Comment by vasily-kirichenko** [comment]
Aha! If I put more specific route first, then it works ok:
```fsharp
route "" >=>  text "a"
routef "/%s/%s/%i/log" (fun (host, app, pid) -> text "foo")
routef "/%s" (fun host -> text "c")
```

**Comment by gerardtoconnor** [comment]
@vasily-kirichenko 
`choose` will iteratively work down the list of routing functions trying to match so if it is able to match before it gets to a more specific rule it will, similar to guards on match statements.

If using the token router, you don't get this issue as it will map all the routes to a tree and order, therefore, doesn't matter.

**Comment by vasily-kirichenko** [comment]
TokenRouter rocks, the code is cleaner too. Thanks!

**Comment by gerardtoconnor** [comment]
Well, the main benefit is speed, it uses hand-rolled parsers as well as radix matching tree so 2x - 3x faster for match/parse ... and has the benefit of not having any `choose` gotchas as maps unique deterministic paths rather than trial and error matches, @forki is a fan too due to its better consistency.
