### ISSUE TITLE
Sucessful.NO_CONTENT

### ISSUE THREAD

**Issue by lenzenmi** [giraffe-fsharp/Giraffe#306]
I'm using Asp.Net.Core 2.1.3 and Giraffe `3.0.0`

A simple handler like this
```
let noContent : HttpHandler =

    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            return! Successful.NO_CONTENT next ctx
            }
```

Throws an exception something like:
```
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
IQ.SaleOverrides.Web>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowWritingToResponseBodyNotSupported()
IQ.SaleOverrides.Web>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
```

This handler works as expected
```
let noContent : HttpHandler =

    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            return! setStatusCode 204 next ctx
            }
```

I believe the error is that the Giraffe implementation tries to write to the body using `setBody`
https://github.com/giraffe-fsharp/Giraffe/blob/a036cfe7d3ef52af68ed1d43b5fe477d4c10a211/src/Giraffe/HttpStatusCodeHandlers.fs#L26

**Comment by dustinmoris** [comment]
Thanks for raising this issue. I confirmed that it didn't work and fixed it for the next upcoming version!
