### ISSUE TITLE
Record Type Serialization not working by default for HttpStatusCodeHandlers

### ISSUE THREAD

**Issue by tangledupinblue** [giraffe-fsharp/Giraffe#360]
Hi, first I just want to say I love Giraffe - thanks to everyone involved.

Having an issue with something that used to work fine - type serialization for record:

```
type  WebItem = { 
    ItemID: string
    }

let getTestDefaultSerializer (next:HttpFunc) (ctx:HttpContext) = 
    Successful.OK { ItemID = "1" } next ctx
```

Expected response - server responded with item serialized in json / xml

Suddenly I am now getting an error:

```
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: ItemApi.WebItem cannot be serialized because it does not have a parameterless constructor.
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at Giraffe.Serialization.Xml.DefaultXmlSerializer.Giraffe-Serialization-Xml-IXmlSerializer-Serialize(Object o) in C:\projects\giraffe\src\Giraffe\Serialization.fs:line 153
   at Giraffe.ResponseWriters.HttpContext.WriteXmlAsync(HttpContext this, Object dataObj) in C:\projects\giraffe\src\Giraffe\ResponseWriters.fs:line 185
   at ItemApi.getTestDefaultSerializer(FSharpFunc`2 next, HttpContext ctx) in /home/barrys/Documents/code/FSharp/custom/lunchhub_hollard/Server/ItemApi.fs:line 54
   at mocca_menu_images.App.webApp@68-5.Invoke(FSharpFunc`2 next, HttpContext ctx) in /home/barrys/Documents/code/FSharp/custom/lunchhub_hollard/Server/Program.fs:line 68
```
I don't think it is a giraffe issue specifically - rather with the default System.Xml.Serialization.XmlSerializer. I think something must have changed in one of the dotnet core updates, but I think this will be an issue for anyone using giraffe and responding to web requests with type lists

I am currently working around this with (haven't figured how to set headers yet)

```
let getTest (next:HttpFunc) (ctx:HttpContext) = 
    json { ItemID = "1" } next ctx
```

**Comment by andagr** [comment]
This started breaking for me when upgrading Giraffe 3.4 -> 3-6.

Fixed "does not have a parameterless constructor" by adding CLIMutable-attribute, but then I'm getting this instead:
![image](https://user-images.githubusercontent.com/1420717/60341477-f4af5000-99ae-11e9-99a6-27ddb90587e9.png)

**Comment by dustinmoris** [comment]
Thanks for reporting, I'm looking into this!

**Comment by slang25** [comment]
I think this is covered in the docs, if you need XML serialisation then you need to add the `CliMutable` attribute.

**Comment by dustinmoris** [comment]
Yes this is correct, also the screenshot above shows that the exception is happening in Thoth.Json.Giraffe, which is a different library. Would be good to report the issue there with a code example of what the `Shared.Counter` type looks like, as this is what Json.NET struggles to serialise.

I don't think that there is anything which we can do here. @andagr does my explanation make sense? Please report this issue [here](https://github.com/MangelMaxime/Thoth/tree/master/src/Thoth.Json.Giraffe) if you haven't done yet and hopefully it can be easily resolved.
