### ISSUE TITLE
Question - how to bind to a dictionary from a FORM POST

### ISSUE THREAD

**Issue by Eevoo** [giraffe-fsharp/Giraffe#435]
Hey all,

Can someone direct me as to resources I could use to bind an HTML form submission that can be bound by ctx.TryBindForm to a record that includes a dictionary as one of the fields? I've made a sample project and all code inside the below linked file, with my snippets below for brevity, but I'm pretty sure I'm doing the form post fields wrong. 

Any advice on how to accomplish this would be appreciated. I need to be able to support just form data, so JSON requests are not an option unfort.

https://github.com/Eevoo/sample-form-post/blob/master/src/sample-dictionary-post/Program.fs
```
// Model in use
[<CLIMutable>] // fix MissingMethodException: No parameterless constructor defined for this object.
type AdventurerDto = 
    {
        name: string
        inventory: Dictionary<string,int>
        // string = item id guid
        // int = how many of that item
}

// views for the page
    let someFormSubmitPage = 
        [
            partial()
            p [] [
                let formFields = 
                    [
                        input [_type "text"; _name "name"; _value "" ;_placeholder "This will bind to 'name' value"]
                        // If I use the below 2 i get Missing value for required property inventory.
                        //input [_type "text"; _name "inventory[key]"; _value "itemid123";_placeholder "This will be the inventory dictionary key"]
                        //input [_type "text"; _name "inventory[value]"; _value "1";_placeholder "This will be the inventory dictionary value"]
                        
                        // if I do it as a single line i get
                        // ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.Int32]'.
                        input [_type "text"; _name "inventory[]"; _value "itemid123,2";_placeholder "This will be the inventory dictionary key + value"]
                        input [_type "submit"; _value "Submit"]
                    ]
                form [ _method "post"; _action "/createAdventurer"] formFields
            ]
] |> layout

// handler that tries the bind today
let postHandler = 
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
                match! ctx.TryBindFormAsync<AdventurerDto>() with
                |Ok abc ->
                    return! text "Yay it worked!" next ctx
                |Error e -> return! text e next ctx
}


```

**Comment by Eevoo** [comment]
Adding a stack trace to give clarity to the implementation below.

I've attempted to make the form input element names match the [ASP.NET core model binding syntax](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#dictionaries) in hopes that I had solved my own problem, unfortunately I instead get the 'Missing value for required property inventory' response instead
```
input [_type "text"; _name "inventory[].Key"; _value "blah"]
input [_type "text"; _name "inventory[].Value"; _value "bleb"]
```

```
System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.Int32]'.

   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)

   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)

   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)

   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)

   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)

   at Giraffe.ModelBinding.ModelParser.error@163.Invoke(FSharpOption`1 error, PropertyInfo prop)

   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222

   at Giraffe.ModelBinding.ModelParser.parseModel[T](T model, FSharpOption`1 cultureInfo, IDictionary`2 data, Boolean strict)

   at Giraffe.ModelBinding.HttpContext-TryBindFormAsync@390-1.Invoke(IFormCollection _arg4)

   at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep)

--- End of stack trace from previous location where exception was thrown ---

```

**Comment by Eevoo** [comment]
THIS IS SOLVED.

User @gfritz has been working on this with me for a while now and came up with the corrections needed. 

1. Use Giraffe 4.x
1. Use .net core 3.1x
1. In the DTO record, replace the field type from Dictionary<'a,'b> to be a type reference to another type. That type should look like a record with two fields, representing the key and value data you want. See https://github.com/Eevoo/sample-form-post/pull/1/files for the specific changes to the example, but a short example is shown below.

```
type [<CLIMutable>] InventoryItem =
    {
        Name: string
        MoneyValue: int // can also be a string or other simple type
    }

[<CLIMutable>]
type AdventurerDto = 
    {
        Name: string
        Inventory: InventoryItem array
    }
```

Have your giraffe view engine code create the HTML elements that make up a form, and have each form element representing a key/value combo be tied together via having the same name as the Dto field you want it bound to, along with an indexing key and sub-fields named = to the field names in the type that used as the array in the Dto field you want.

```
input [_type "text"; _name "Inventory[0].Name"; _value "bag of goods"]
input [_type "number"; _name "Inventory[0].MoneyValue"; _value "5"]
input [_type "text"; _name "Inventory[1].Name"; _value "human toenail clipping"]
input [_type "number"; _name "Inventory[1].MoneyValue"; _value "0"]
input [_type "text"; _name "Inventory[2].Name"; _value "werewolf zester"]
input [_type "number"; _name "Inventory[3].MoneyValue"; _value "9001"]
```

The returned html elements look like the below:
```
<input type="text" name="Inventory[0].Name" value="bag of goods">
<input type="number" name="Inventory[0].MoneyValue" value="5">
<input type="text" name="Inventory[1].Name" value="human toenail clipping">
<input type="number" name="Inventory[1].MoneyValue" value="0">
<input type="text" name="Inventory[2].Name" value="werewolf zester">
<input type="number" name="Inventory[3].MoneyValue" value="9001">
```
Screenshot:
![image](https://user-images.githubusercontent.com/49214133/86146939-cc2ccb00-bac6-11ea-86dd-8f6efe530a21.png)

A quick n dirty way of creating the needed input elements is pasted below. The output of the below function would be concatenated to whatever other form fields are already present in giraffe view engine via list concatenation.
```
        /// Given a list of tuples, returns an XmlNodeList of form inputs that can be bound to a field in a Dto
        let CreateDictionaryBindableInput (keyValues: (string * string) list) (bindFieldName) = 
            let mutable retValue = []
            let mutable iteration = 0
            for kvp in keyValues do
                let calculatedName = bindFieldName + "[" + iteration.ToString() + "]"
                let calculatedKeyName = calculatedName + ".Name" // AKA ".Key", would be better as a parameter named keyFieldName
                let calculatedValueName = calculatedName + ".MoneyValue" //".Value", would be better as valueFieldName
                match kvp with
                |k,v -> 
                    let key = input [_type "text"; _name calculatedKeyName; _value k]
                    let vl = input [_type "number"; _name calculatedValueName; _value v]
                    iteration <- iteration + 1
                    retValue <- retValue @ [key; vl]
            retValue
```

And finally, to bind them, you perform something similar to the below in your Giraffe handler.

```
let postHandler = 
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
                match! ctx.TryBindFormAsync<AdventurerDto>() with
                |Ok abc ->
                    return! text "Yay it worked! Why do you have toenail clippings...? gross" next ctx
                |Error e -> return! text e next ctx
            }
