### ISSUE TITLE
Guid pattern in endpoint router matches invalid values, throws System.FormatException

### ISSUE THREAD

**Issue by jcmrva** [giraffe-fsharp/Giraffe#576]
Our fuzzer discovered some values that will match the endpoint router's [regex](https://github.com/giraffe-fsharp/Giraffe/blob/6a364955f77609e9265c577ddd817c92fefe104c/src/Giraffe/EndpointRouting.fs#L16) behind `%O`.

App code:
```fsharp
GET [ routef "/try-a-guid/%O" (fun (guid: Guid) -> text $"Success: {guid}" ) ]
```

Test:
```fsharp
#r "nuget: FsHttp"
open FsHttp

let fuzzerInput = "8b3557db-fa-c0c90785ec0b"
http {
    GET $"http://localhost:5000/try-a-guid/{fuzzerInput}"
}
|> Request.send
```

```text
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/try-a-guid/8b3557db-fa-c0c90785ec0b - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /try-a-guid/{O0:regex(([0-9A-Fa-f]{{8}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{12}}|[0-9A-Fa-f]{{32}}|[-_0-9A-Za-z]{{22}}))}'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /try-a-guid/{O0:regex(([0-9A-Fa-f]{{8}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{4}}\-[0-9A-Fa-f]{{12}}|[0-9A-Fa-f]{{32}}|[-_0-9A-Za-z]{{22}}))}'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN1J1DK6DFOF", Request id "0HN1J1DK6DFOF:00000001": An unhandled exception was thrown by the application.
      System.FormatException: Unrecognized Guid format.
         at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
         at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
         at System.Guid..ctor(String g)
         at Giraffe.EndpointRouting.RequestDelegateBuilder.parseGuid@56-1(String s)
         at Giraffe.EndpointRouting.RequestDelegateBuilder.tryGetParser@68-6.Invoke(String x)
         at Giraffe.EndpointRouting.RequestDelegateBuilder.convertToTuple(FSharpList`1 mappings, RouteData routeData)
         at Giraffe.EndpointRouting.RequestDelegateBuilder.createTokenizedRequestDelegate@111-1.MoveNext()
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/try-a-guid/8b3557db-fa-c0c90785ec0b - 500 0 - 14.3764ms
```

Full repro [here](https://github.com/jcmrva/giraffe-guid-route).

One workaround is adding middleware to catch `FormatException`.

dotnet sdk 8.0.200
Giraffe 6.2.0

**Comment by ronnieholm** [comment]
What's the behavior you're after? Why do you consider the above a bug?

**Comment by jcmrva** [comment]
We'd rather it return a 400, and IMO in general, user input should not result in unhandled exceptions.

**Comment by 64J0** [comment]
The error is happening here apparently: https://github.com/giraffe-fsharp/Giraffe/blob/develop/src/Giraffe/EndpointRouting.fs#L56

**Comment by 64J0** [comment]
Feel free to add your review to this PR https://github.com/giraffe-fsharp/Giraffe/pull/594

**Comment by 64J0** [comment]
Giraffe version `6.4.1-alpha-3` has the fix. I tested locally, and it's not matching the wrong Guid. Please let me know if there's something else regarding this issue @jcmrva.

**Comment by jcmrva** [comment]
Looks good to me. Thanks!
